mots_francais_var = {
    "a": ["ami", "arbre", "avion", "a", "as", "ai", "au", "aux", "avec", "avant"],
    "b": ["bateau", "ballon", "banane", "bien", "beaucoup"],
    "c": ["chat", "chien", "chaise", "ce", "cet", "cette", "ces", "comme", "chez"],
    "d": ["dame", "dent", "doigt", "de", "du", "des", "dans", "donc"],
    "e": ["eau", "école", "éléphant", "et", "est", "es", "être", "en"],
    "f": ["fleur", "fromage", "feuille", "fait", "font"],
    "g": ["gâteau", "gare", "guitare", "grand"],
    "h": ["homme", "hôtel", "histoire", "il", "ils"],
    "i": ["image", "île", "insecte", "ici", "il", "ils"],
    "j": ["jardin", "jouet", "journal", "je", "j'", "jusqu"],
    "k": ["kiwi", "kilo"],
    "l": ["livre", "lampe", "lune", "le", "la", "les", "lui", "leur"],
    "m": ["maison", "mère", "montagne", "mon", "ma", "mes", "mais", "même","malade"],
    "n": ["nez", "nuage", "nuit", "nous", "notre", "nos"],
    "o": ["ordinateur", "orange", "oiseau", "ou", "où", "on"],
    "p": ["pomme", "porte", "parle", "pour", "pas", "plus", "peut"],
    "q": ["question", "queue", "que", "qui", "quoi", "quand"],
    "r": ["route", "roi", "rivière", "rien", "rendre"],
    "s": ["soleil", "stylo", "sac", "suis", "es", "est", "sommes", "sont", "sur", "se", "sa", "ses"],
    "t": ["table", "téléphone", "train", "tu", "te", "ton", "ta", "tes", "très"],
    "u": ["usine", "univers", "utile", "un", "une"],
    "v": ["voiture", "ville", "vent", "vais", "va", "vont", "voir"],
    "w": ["wagon"],
    "x": ["xylophone"],
    "y": ["yaourt", "y"],
    "z": ["zèbre", "zéro"]
}